// Generated by scripts/cutout.py from the Heavenly Gate's images (M10 gate §2). Do not edit.
/** gate-post-top-2's size in pixels. */
export const POST_TOP_W = 1536;
export const POST_TOP_H = 2752;
/** The crown's base band, in pixels across: it spans the 4 m crown box. */
export const CROWN_BASE_PX = 1028;
/** The crown's widest row (its horn tips): its first column and the one past its last. */
export const CROWN_WIDE: readonly [number, number] = [100, 1436];
/** The crown's top: the topmost row of the outer horn tips. */
export const CROWN_TOP_ROW = 2026;
/** Everything above the crown's top (struts, ring, spire): its first column and the one past its last. */
export const SPIRE_COLS: readonly [number, number] = [536, 1001];
/** gate-leaves' outer edges' top within 0.5 m of each side, as a fraction of the leaves' height. */
export const LEAVES_EDGE_TOP = 0.8576;
/** The post shaft's repeat height in meters on a 3 m shaft. */
export const SHAFT_REPEAT = 5.3344;
