// Generated by scripts/cutout.py from the sky painting (M10 §4.2). Do not edit.
export const SKY_WIDTH = 2701;
export const SKY_HEIGHT = 1344;
/** The row where the cloud sea meets the haze, in pixels from the top. */
export const SKY_HORIZON_ROW = 874;
export const SKY_TOP_COLOR = 0x4586cd;
export const SKY_BOTTOM_COLOR = 0xe5d9c3;
export const SKY_HORIZON_COLOR = 0xe1d9bb;
export const SKY_ZENITH_COLOR = 0x2e7dd1;
